Styling
psu-libraries/etda_explore pull request #41
Opened 2022-06-14 19:11 UTC by ajkiessl

Basic styling to match ETDA Workflow, and look like a PSU Libraries site.  I took the path of least resistance and changed as little as possible.  I'm open to suggestions to make it look better if we think that's needed.

![Screen Shot 2022-06-14 at 3 09 36 PM](https://user-images.githubusercontent.com/32677188/173669745-73b1b0df-e37f-47f6-9d61-d869530fd33e.png)

I need to update etda_utilities before this gets merged.

closes #4

2022-06-14 20:48 UTC, whereismyjetpack requested changes

2022-06-14 20:52 UTC, ajkiessl commented on app/models/workflow_url.rb
> +        ENV['WORKFLOW_HOST'] || 'prod'
Oh right, I'll fix this.

2022-06-14 21:06 UTC, ajkiessl commented on app/models/workflow_url.rb
> +        ENV['WORKFLOW_HOST'] || 'prod'
Might as well try to refactor this into utilities tomorrow.

2022-06-15 18:48 UTC, banukutlu approved these changes
this looks good to me 👍🏻 once the lint issues get fixed and with the WORKFLOW_HOST refactor, it is a good start, we can always add on as needed. thanks @ajkiessl!

2022-06-15 19:32 UTC, ajkiessl commented
This also closes #26 .  I added the 'Add My Work' link since it uses the WORKFLOW_HOST.  While I was doing that, I decided just to finish up #26 and add the about page.  I don't think we need a 'Home' link since we don't really have a home page.  

I'm going to get https://github.com/psu-stewardship/etda_utilities/pull/20 merged and update etda_utilities.  This should be ready to go after that.

2022-06-15 20:10 UTC, whereismyjetpack approved these changes

2022-06-16 12:48 UTC, merged